# Generated by Django 3.2.10 on 2021-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('guid', models.UUIDField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('Status', models.IntegerField(choices=[(0, 'NOTHING'), (1, 'MODIFY_SUPPORT'), (2, 'MODIFY_UN_SUPPORT')], default=0)),
                ('is_disable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
