# Generated by Django 3.2.10 on 2021-12-10 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rssdriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
