# Generated by Django 3.2.10 on 2021-12-15 06:10
from django.db import migrations, models
from rssdriver.models import Channel

from user.models import User

items = [
    {
        'title': 'lincolnproject', 'link': 'https://lincolnproject.libsyn.com/rss'
    }
    ,
    {
        'title': 'fireside', 'link': 'https://feeds.fireside.fm/bibleinayear/rss'
    }

]


def create_mock_data_app(apps, schema_editor):
    """create user ,channel and article mock data"""
    User.objects.create_superuser('admin','admin')
    for item in items:
        item_obj = Channel.objects.create(
            title=item['title'],
            link=item['link']
        )
        Channel.get_chanel_info.delay(item_obj)



def drop_mock_data_app(apps, schema_editor):
    """drop user ,channel"""

    User.objects.filter(username='admin').delete()
    for item in items:
        Channel.objects.filter(link=item['link']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rssdriver', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(
            create_mock_data_app,
            reverse_code=drop_mock_data_app,

        ),
    ]
