# Generated by Django 3.2.10 on 2021-12-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssdriver', '0003_article_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='Status',
            new_name='status',
        ),
    ]
